spring:
  application:
    name: room_manager
  data:
    mongodb:
      uri: mongodb://admin:admin@onliver.ru:27017/room?authSource=admin&authMechanism=SCRAM-SHA-256
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      name: room-events
      partitions: 1
      replication-factor: 1
    properties:
      security:
        protocol: PLAINTEXT

server:
  port: 8080
  ssl:
    enabled: false

livekit:
  host: http://onliver.ru:7880
  apiKey: APIXMCTJEXDBghU
  secret: laxpDMZwSmNlxvjHzG8YnZsti8ofCMRlY9H6OAL7EeL


