name: CI/CD Deployment

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  IMAGE_NAME: isdockero/onliver-room-manager
  IMAGE_TAG: latest          # при желании замените на ${{ github.sha }}
  REGISTRY: docker.io        # или ghcr.io

jobs:
  # -------------------------- 1. СБОРКА --------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3   # клонируем репозиторий
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build (compile)
        run: mvn -B package -DskipTests

  # -------------------------- 2. ТЕСТЫ ---------------------------
  test:
    runs-on: ubuntu-latest
    needs: build                   # ждём окончания build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run unit tests
        run: mvn -B test

  # -------------------------- 3. DOCKER --------------------------
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./room_manager
          file: ./room_manager/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  # -------------------------- 4. ДЕПЛОЙ --------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    environment: production        # красивый «Deployment» в UI
    steps:
      - name: Stop running stack & clean up
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker stack rm onliver_room_manager_stack || true
            sleep 15
            sudo rm -rf ~/deploy || true

      - name: Copy 'deploy' directory to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'deploy/*'
          target: '~/'

      - name: Deploy new stack
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker stack deploy --detach=true \
              -c ~/deploy/docker-compose.yaml onliver_room_manager_stack
